//
// Created by dylan on 29/03/2017.
//

#ifndef COMPILERTHEORY_ASTFUNCTIONDECLARATION_H
#define COMPILERTHEORY_ASTFUNCTIONDECLARATION_H


class ASTFunctionDeclaration {

};


#endif //COMPILERTHEORY_ASTFUNCTIONDECLARATION_H
